# Generated by Django 4.2.7 on 2023-11-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_traineruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerUser',
        ),
    ]
