# Generated by Django 4.2.7 on 2023-11-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_trainingsessions1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribesessions',
            name='Sessions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainingsessions1'),
        ),
    ]
